### ISSUE TITLE
[PE-D][Tester D] Error message for using celebrity as point of contact slightly unclear.

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W12-4/tp#240]
![Untitled2.png](https://raw.githubusercontent.com/yixianggg/ped/main/files/8ffca633-8272-4368-b406-ff5d39cc614d.png)

In the image above, the error message states: Celebrity cannot be a contact in contact list. However, this can be slightly unclear and misleading as a person with the celebrity tag can be a contact in the contact list, just not if they are the celebrity in question attending the event. For instance, `add event n/Brand Breakfast t/2015-02-20 07:31 to 2015-02-20 08:30 c/Alex Yeoh p/Bernice Yu` would work perfectly fine. May want to consider just changing the error message slightly for more clarity.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: yixianggg/ped#5

**Comment by Haris-Irfan** [comment]
Specify message to explain that the current celebrity involved in the event cannot be part of the contacts list
