### ISSUE TITLE
[PE-D][Tester E] Large Integer Input Breaks delete Command Functionality

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W12-4/tp#281]
**Description:**
When using the delete command in TalentNet, entering a large integer (specifically, any number greater than 2147483647) as the index results in an "Invalid command format" error. For instance, the command delete person 2147483648 returns an unexpected error message instead of handling the integer properly or indicating that the index is out of range. This issue likely stems from the integer limit on the command input, leading to a confusing user experience for numbers exceeding this limit.

**Steps to Reproduce:**

1. Open the TalentNet app.
2. Attempt to delete a contact using a large integer as the index, e.g., delete person 2147483648.
3. Attempt to delete a contact using a integer within the largest Java Integer range as the index, e.g., delete person 2147483647.
4. Compare the results returned by the app.

**Expected Documentation or Expected Result:**
Expected Documentation: Maybe mention in the documentation that the largest possible index value entered would be 2147483647.
Or the app should either:
Return an "Index out of range" message if the number exceeds the valid range of existing contact indexes.

Handle the large integer gracefully and clarify that the index is invalid or too large.

**Actual Result:**
The app displays the following error message, which suggests a formatting issue instead of clearly addressing the out-of-range number:
Invalid command format! delete person: Deletes the person identified by the index number used in the displayed person list. Parameters: INDEX (must be a positive integer) Example: delete person 1

**Screenshot**

![image.png](https://raw.githubusercontent.com/zhou-colla/ped/main/files/e7d596ba-792a-4ca2-853d-b7df37fe8b52.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: zhou-colla/ped#6

**Comment by seantham21** [comment]
Will also add a note in the UG about the maximum number of persons the app can manage.
